# DataSource settings: set here your own configurations for the database
# connection. In this example we have "netgloo_blog" as database name and
# "root" as username and password.
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pinetdev?createDatabaseIfNotExist=true
    username: root
    password: Test1234
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL5Dialect
  h2:
    console:
      enabled: true


liquibase:
  change-log: classpath:db/changelog/changelog.xml


#logging
logging:
    file: src/main/resources/logs/application.log
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


