# DataSource settings: set here your own configurations for the database
# connection. In this example we have "netgloo_blog" as database name and
# "root" as username and password.
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pinetdev?createDatabaseIfNotExist=true
    username: root
    password: system
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL5Dialect
  h2:
    console:
      enabled: true

  output:
    ansi:
        enabled: ALWAYS

  thymeleaf:
    cache: false

#messaging
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: tiwaryashmeet@gmail.com
    password: Pokhara98254
    port: 587
#    host: mailrelay.intranet.hdp.be
#    username: test
#    password: test
#    port:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
    protocol: smtp
    test-connection: false



liquibase:
  change-log: classpath:db/changelog/changelog.xml

#spring.output.ansi.enabled=always
#spring.main.banner-mode=off
#logging
logging:
    file: src/main/resources/logs/application.log
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


