spring:
  profiles.active: dev

spring:
  profiles: dev
logging:
  file: src/main/resources/logs/dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    com.pinet.app.web.controller: DEBUG
    org.hibernate: DEBUG